### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by jbonde** [sleggat/TallyHo#2]
What would be the correct formatting in config.php of public static $defaultDateFormat = 'Y-m-d h:i A';
for using 24hrs instead of AM/PM?

**Comment by sleggat** [comment]
Hi Jesper, I'm just got back from holiday so I apologise for not getting back to you sooner. 
I must admit the date/time formatting is only half-done right now. I'll try and get that sorted out this week.

**Comment by sleggat** [comment]
I've added this line to the config which should be what you're after:
`public static $defaultTimeFormat = 'g:ia'; // 'g:ia' returns 01:23pm, 'H:i' returns 13:23`
