### ISSUE TITLE
Warning when deleting

### ISSUE THREAD

**Issue by jbonde** [sleggat/TallyHo#3]
Warning: DateTime::modify(): Failed to parse time string (- minutes) at position 0 (-): Unexpected character in /nfs/c03/h04/mnt/170464/domains/tallyho.steveleggat.com/html/guts/functions.php on line 172

Warning: date_format() expects parameter 1 to be DateTimeInterface, bool given in /nfs/c03/h04/mnt/170464/domains/tallyho.steveleggat.com/html/guts/functions.php on line 172

**Comment by sleggat** [comment]
Thanks for bringing it to my attention. I think it's just a permissions issue on the demo server, but I'll keep this issue Open until I sort that out.

**Comment by sleggat** [comment]
Turned out to be a problem with the recent caching I implemented. i.e. it was thinking those tasks were still there. I'm not deleting the cache file after delete/update/adding of tasks.
Thanks again.
